{{- range .Values.teams }}
---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: appset-{{ .name }}
  namespace: argocd
spec:
  goTemplate: true
  generators:
    - matrix:
        generators:
          - git:
              repoURL: "{{ $.Values.repositoryUrl }}"
              revision: "{{ $.Values.targetRevision }}"
              directories:
                - path: apps/sbx/{{ .name }}/*
          - list:
              elements:
                {{- if .apps }}
                {{- range $appName, $app := .apps }}
                - appName: {{ $appName | quote }}
                  annotations: {{ $app.annotations | toJson }}
                {{- end }}
                {{- else }}
                - appName: "{{ printf "{{.path.basename}}" }}"
                  annotations: {}
                {{- end }}
  template:
    metadata:
      name: "{{ .name }}-{{ printf "{{.path.basename}}" }}-{{ printf "{{.appName}}" }}"
    spec:
      project: default
      source:
        repoURL: "{{ $.Values.repositoryUrl }}"
        targetRevision: "{{ $.Values.targetRevision }}"
        path: "apps/sbx/{{ .name }}/{{ printf "{{.path.basename}}" }}"
        helm:
          valueFiles:
            - values.yaml
      destination:
        server: https://kubernetes.default.svc
        namespace: "sbx-{{ .name }}-{{ printf "{{.path.basename}}" }}"
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
  templatePatch: |
    {{ printf "{{- if eq .path.basename .appName }}" }}
    metadata:
      annotations:
      {{ printf "{{- toYaml .annotations | nindent 8 }}" }}
    {{ printf "{{- else }}" }}
    spec:
      source:
        repoURL: "invalid"
    {{ printf "{{- end }}" }}
{{- end }}