helm:
  parameters:
  - name: image.repository
    value: loibinomiale/nginx
    forcestring: true
  - name: image.tag
    value: rc-2.3.5
    forcestring: true
  - name: sidecarImage.repository
    value: loibinomiale/hello-world
    forcestring: true
  - name: sidecarImage.tag
    value: v3.4.0
    forcestring: true
