helm:
  parameters:
  - name: image.repository
    value: loibinomiale/nginx
    forcestring: true
  - name: image.tag
    value: rc-4.9.0
    forcestring: true
  - name: sidecarImage.repository
    value: loibinomiale/hello-world
    forcestring: true
  - name: sidecarImage.tag
    value: v8.4.0
    forcestring: true
