helm:
  parameters:
  - name: image.repository
    value: loibinomiale/nginx
    forcestring: true
  - name: image.tag
    value: rc-3.3.7
    forcestring: true
  - name: sidecarImage.repository
    value: loibinomiale/hello-world
    forcestring: true
  - name: sidecarImage.tag
    value: v7.4.0
    forcestring: true
