{{- range .Values.teams }}
---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: appset-{{ .name }}
  namespace: argocd
spec:
  goTemplate: true
  generators:
    - list:
        elements:
{{- $team := .name }}
{{- range .apps }}
          - name: {{ .name }}
            argoName: {{ .argoName }}
            team: {{ $team }}
            path: apps/sbx/{{ $team }}/{{ .name }}
            namespace: sbx-{{ $team }}-{{ .name }}
            annotations:
{{ toYaml .annotations | indent 14 }}
{{- end }}
  template:
    metadata:
      name: "{{ $team }}-{{ printf "{{.name}}" }}"
      annotations:
        {{- toYaml .annotations | nindent 8 }}
    spec:
      project: default
      source:
        repoURL: "{{ $.Values.repositoryUrl }}"
        targetRevision: "{{ $.Values.targetRevision }}"
        path: "{{ printf "{{.path }}"}}"
        helm:
          valueFiles:
            - values.yaml
      destination:
        server: https://kubernetes.default.svc
        namespace: "{{ .namespace }}"
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
{{- end }}
