{{- range .Values.teams }}
---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: appset-{{ .name }}
  namespace: argocd
spec:
  goTemplate: true
  generators:
    - matrix:
        generators:
          - git:
              repoURL: "{{ $.Values.repositoryUrl }}"
              revision: "{{ $.Values.targetRevision }}"
              directories:
                - path: apps/sbx/{{ .name }}/*
          - list:
              elements:
                {{- range $appName, $app := .apps }}
                - appName: {{ $appName | quote }}
                  annotations: {{ $app.annotations | toJson }}
                {{- end }}
  template:
    metadata:
      name: "{{ .name }}-{{ printf "{{.path.basename}}" }}"
    spec:
      project: default
      source:
        repoURL: "{{ $.Values.repositoryUrl }}"
        targetRevision: "{{ $.Values.targetRevision }}"
        path: "apps/sbx/{{ .name }}/{{ printf "{{.path.basename}}" }}"
        helm:
          valueFiles:
            - values.yaml
      destination:
        server: https://kubernetes.default.svc
        namespace: "sbx-{{ .name }}-{{ printf "{{.path.basename}}" }}"
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
  templatePatch: |
    metadata:
      annotations:
      {{ print "{{- toYaml .annotations | nindent 8 }}"}}
{{- end }}