repositoryUrl: git@github.com:lucmahoux/poc-template-appset-argocd.git
targetRevision: main

teams:
  - name: annotations
    apps:
      webapp:
        annotations:
          custom.annotation.io/component: web
      billing:
        annotations:
          custom.annotation.io/component: payment
          custom.annotation.io/team: alpha
  - name: no-annotations
    apps: {}
  - name: mixed
    apps:
      billing:
        annotations:
          custom.annotation.io/component: payment
          custom.annotation.io/team: mixed