repositoryUrl: git@github.com:lucmahoux/poc-template-appset-argocd.git
targetRevision: main

teams:
  - name: alpha
    apps:
      webapp:
        annotations:
          custom.annotation.io/component: web
      billing:
        annotations:
          custom.annotation.io/component: payment
          custom.annotation.io/team: alpha
  - name: beta
    apps: {}
