repositoryUrl: git@github.com:lucmahoux/poc-template-appset-argocd.git
targetRevision: main

teams:
  - name: alpha
    apps:
      - name: webapp
        argoName: frontend
        annotations:
          custom.annotation.io/component: web
      - name: billing
        argoName: billing-api
        annotations:
          custom.annotation.io/component: payment
          custom.annotation.io/team: alpha
